### ISSUE TITLE
Failed to activate the linter-cwl package

### ISSUE THREAD

**Issue by manabuishii** [manabuishii/linter-cwl#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [linter-cwl](https://github.com/manabuishii/linter-cwl) package 0.4.0

### Stack Trace

Failed to activate the linter-cwl package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-cwl/index.js:3:31)
    at /packages/linter-cwl/index.js:105:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:903:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:242:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -0:16 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-cwl 0.3.0 
busy-signal 1.4.3 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.10.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-cwl 0.6.0 
language-cwl-atom 0.0.1 
language-lua 0.9.11 
linter 2.2.0 
linter-cwl 0.4.0 
linter-ui-default 1.6.10 
markdown-preview-plus 2.4.16 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
project-manager 3.3.5 
remote-atom 1.3.11 
Remote-FTP 1.2.6 
tree-view-filter 0.5.3 
tree-view-git-status 1.4.0 
```

**Comment by manabuishii** [comment]
Fix at 0.5.0 (I hope)
